variables:
  GIT_SUBMODULE_STRATEGY: recursive
  
test_ffi_cpp_linux:
  script:
    - nim cpp --cincludes:. -r fragments/ffi/cpp.nim
    - nim c -r fragments/dsl.nim
    - nim c --threads:on -r fragments/threading/threading_primitives.nim
    - nim c --threads:on -r fragments/threading/atomics.nim
    - nim cpp --threads:on -r fragments/threading/atomics.nim
    - nim c -r fragments/math/linalg.nim
    - nim c -r fragments/math/vectors.nim
    - nim c -r fragments/serialization.nim
    - nim c -r fragments/seqview.nim
  tags:
    - NIM, LINUX
    
test_ffi_cpp_win_vcc:
  script:
    - nim e build_win_ci.nims # refer to build_win_ci.nims
  tags:
    - NIM, WIN10
