variables:
  GIT_SUBMODULE_STRATEGY: recursive
  
test_ffi_cpp_linux:
  script:
    - nim cpp --cincludes:. -r core/ffi/cpp.nim
  tags:
    - NIM, LINUX
    
test_ffi_cpp_win_vcc:
  script:
    - nim e build_win_ci.nims # refer to build_win_ci.nims
  tags:
    - NIM, WIN10